[package]
name = "mc-server-installer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.3", features = ["derive", "env"] }
futures-util = { version = "0.3.28", features = ["io", "tokio-io"] }
log = "0.4.18"
reqwest = { version = "0.11.18", features = ["stream"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"
simplelog = "0.12.1"
tokio = { version = "1.28.2", features = ["full"] }
