name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release - ${{ matrix.platform.os_name }}
    permissions:
      contents: write
    strategy:
      matrix:
        platform:
          - os_name: Linux-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            binary: mc-server-installer
            
          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            binary: mc-server-installer.exe

    runs-on: ${{ matrix.platform.os }}
    
    steps:
    - name: checkout
      uses: actions/checkout@v4
      
    - name: rustup toolchain install
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
        targets: ${{ matrix.platform.target }}

    - name: build
      uses: actions-rs/cargo@v1.0.1
      with:
        command: build
        args: --release --target ${{ matrix.platform.target }}

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform.os_name }}
        path: target/${{ matrix.platform.target }}/release/${{ matrix.platform.binary }}
