name: Release

on:
  push:
    branches: ["release"]
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    permissions:
      contents: write
    strategy:
      matrix:
        platform:
          - os_name: Linux-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            binary: mc-server-installer
            
          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            binary: mc-server-installer.exe

    runs-on: ${{ matrix.platform.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: rustup toolchain install
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          targets: ${{ matrix.platform.target }}

      - name: build
        uses: actions-rs/cargo@v1.0.1
        with:
          command: build
          args: --release --target ${{ matrix.platform.target }}

      - name: Upload release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: target/${{ matrix.platform.target }}/release/${{ matrix.platform.binary }}
          generate_release_notes: true
