name: Rust

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release - ${{ matrix.platform.os_name }}
    strategy:
      matrix:
        platform:
          - os_name: Linux-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            
          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.platform.os }}
    
    steps:
    - name: checkout
      uses: actions/checkout@v3
      
    - name: rustup toolchain install
      uses: dtolnay/rust-toolchain@v1
      with:
        targets: ${{ matrix.platform.target }}

    - name: build
      uses: actions-rs/cargo@v1.0.1
      with:
        command: build
        args: --release --target ${{ matrix.platform.target }}
  
    - name: package build
      uses: TheDoctor0/zip-release@0.7.1
      with:
        filename: ${{ matrix.platform.os_name }}.zip
        path: target/${{ matrix.platform.target }}/release

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ matrix.platform.os_name }}
        path: ${{ matrix.platform.os_name }}.zip
